openapi: 3.2.0
info:
  title: Shopify Collect API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Collect
paths:
  /admin/api/2020-01/collects/{collect_id}.json:
    get:
      summary: Shopify Retrieves A Specific Collect By Its Id
      description: https://shopify.dev/docs/admin-api/rest/reference/products/collect#show-2020-01
      parameters:
      - in: path
        name: collect_id
        required: true
        schema:
          type: string
        description: collect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Collect
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_collects_param_collect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/collects/{collect_id}.json:
    get:
      summary: Shopify Retrieves A Specific Collect By Its Id
      description: https://shopify.dev/docs/admin-api/rest/reference/products/collect#show-2020-04
      parameters:
      - in: path
        name: collect_id
        required: true
        schema:
          type: string
        description: collect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Collect
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_collects_param_collect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/collects/{collect_id}.json:
    get:
      summary: Shopify Retrieves A Specific Collect By Its Id
      description: https://shopify.dev/docs/admin-api/rest/reference/products/collect#show-2020-07
      parameters:
      - in: path
        name: collect_id
        required: true
        schema:
          type: string
        description: collect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Collect
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_collects_param_collect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/collects/{collect_id}.json:
    get:
      summary: Shopify Retrieves A Specific Collect By Its Id
      description: https://shopify.dev/docs/admin-api/rest/reference/products/collect#show-2020-10
      parameters:
      - in: path
        name: collect_id
        required: true
        schema:
          type: string
        description: collect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Collect
      responses:
        '200':
          description: ''
      operationId: get_collects_param_collect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/collects/{collect_id}.json:
    get:
      summary: Shopify Retrieves A Specific Collect By Its Id
      description: https://shopify.dev/docs/admin-api/rest/reference/products/collect#show-2021-01
      parameters:
      - in: path
        name: collect_id
        required: true
        schema:
          type: string
        description: collect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Collect
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_collects_param_collect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/collects/{collect_id}.json:
    get:
      summary: Shopify Retrieves A Specific Collect By Its Id
      description: https://shopify.dev/docs/admin-api/rest/reference/products/collect#show-unstable
      parameters:
      - in: path
        name: collect_id
        required: true
        schema:
          type: string
        description: collect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Collect
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_collects_param_collect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
