openapi: 3.2.0
info:
  title: Shopify Script API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Script
paths:
  /admin/api/2020-01/script_tags.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    event: onload
                    src: https://djavaskripped.org/fancy.js
                summary: Create a new script tag
              example2:
                value:
                  script_tag:
                    body: foobar
                summary: Creating a script tag without a src and event will return an error
      summary: Shopify Creates A New Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#create-2020-01
      parameters: []
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_script_tags
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/script_tags/{script_tag_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    id: 596726825
                    src: https://somewhere-else.com/another.js
                summary: Update a script tag's URL
      summary: Shopify Updates A Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#update-2020-01
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_update_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/script_tags.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    event: onload
                    src: https://djavaskripped.org/fancy.js
                summary: Create a new script tag
              example2:
                value:
                  script_tag:
                    body: foobar
                summary: Creating a script tag without a src and event will return an error
      summary: Shopify Creates A New Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#create-2020-04
      parameters: []
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_script_tags
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/script_tags/{script_tag_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    id: 596726825
                    src: https://somewhere-else.com/another.js
                summary: Update a script tag's URL
      summary: Shopify Updates A Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#update-2020-04
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_update_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/script_tags.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    event: onload
                    src: https://djavaskripped.org/fancy.js
                summary: Create a new script tag
              example2:
                value:
                  script_tag:
                    body: foobar
                summary: Creating a script tag without a src and event will return an error
      summary: Shopify Creates A New Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#create-2020-07
      parameters: []
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_script_tags
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/script_tags/{script_tag_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    id: 596726825
                    src: https://somewhere-else.com/another.js
                summary: Update a script tag's URL
      summary: Shopify Updates A Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#update-2020-07
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_update_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/script_tags.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    event: onload
                    src: https://djavaskripped.org/fancy.js
                summary: Create a new script tag
              example2:
                value:
                  script_tag:
                    body: foobar
                summary: Creating a script tag without a src and event will return an error
      summary: Shopify Creates A New Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#create-2020-10
      parameters: []
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: create_script_tags
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/script_tags/{script_tag_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    id: 596726825
                    src: https://somewhere-else.com/another.js
                summary: Update a script tag's URL
      summary: Shopify Updates A Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#update-2020-10
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: update_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/script_tags.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    event: onload
                    src: https://djavaskripped.org/fancy.js
                summary: Create a new script tag
              example2:
                value:
                  script_tag:
                    body: foobar
                summary: Creating a script tag without a src and event will return an error
      summary: Shopify Creates A New Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#create-2021-01
      parameters: []
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_script_tags
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/script_tags/{script_tag_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    id: 596726825
                    src: https://somewhere-else.com/another.js
                summary: Update a script tag's URL
      summary: Shopify Updates A Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#update-2021-01
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_update_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/script_tags.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    event: onload
                    src: https://djavaskripped.org/fancy.js
                summary: Create a new script tag
              example2:
                value:
                  script_tag:
                    body: foobar
                summary: Creating a script tag without a src and event will return an error
      summary: Shopify Creates A New Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#create-unstable
      parameters: []
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_script_tags
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/script_tags/{script_tag_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  script_tag:
                    id: 596726825
                    src: https://somewhere-else.com/another.js
                summary: Update a script tag's URL
      summary: Shopify Updates A Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#update-unstable
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      tags:
      - Script
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_update_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
