openapi: 3.2.0
info:
  title: Shopify Redirect API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Redirect
paths:
  /admin/api/2020-01/redirects.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  redirect:
                    path: /ipod
                    target: /pages/itunes
                summary: Create a redirect
              example2:
                value:
                  redirect:
                    path: http://www.apple.com/forums
                    target: http://forums.apple.com
                summary: Create a redirect using a full URL for the path, which will be saved as an absolute path without a domain
              example3:
                value:
                  redirect:
                    body: foobar
                summary: Creating a redirect without a path or target fails and returns an error
      summary: Shopify Creates A Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#create-2020-01
      parameters: []
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_redirects
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/redirects/{redirect_id}.json:
    get:
      summary: Shopify Retrieves A Single Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#show-2020-01
      parameters:
      - in: path
        name: redirect_id
        required: true
        schema:
          type: string
        description: redirect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_redirects_param_redirect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/redirects.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  redirect:
                    path: /ipod
                    target: /pages/itunes
                summary: Create a redirect
              example2:
                value:
                  redirect:
                    path: http://www.apple.com/forums
                    target: http://forums.apple.com
                summary: Create a redirect using a full URL for the path, which will be saved as an absolute path without a domain
              example3:
                value:
                  redirect:
                    body: foobar
                summary: Creating a redirect without a path or target fails and returns an error
      summary: Shopify Creates A Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#create-2020-04
      parameters: []
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_redirects
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/redirects/{redirect_id}.json:
    get:
      summary: Shopify Retrieves A Single Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#show-2020-04
      parameters:
      - in: path
        name: redirect_id
        required: true
        schema:
          type: string
        description: redirect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_redirects_param_redirect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/redirects.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  redirect:
                    path: /ipod
                    target: /pages/itunes
                summary: Create a redirect
              example2:
                value:
                  redirect:
                    path: http://www.apple.com/forums
                    target: http://forums.apple.com
                summary: Create a redirect using a full URL for the path, which will be saved as an absolute path without a domain
              example3:
                value:
                  redirect:
                    body: foobar
                summary: Creating a redirect without a path or target fails and returns an error
      summary: Shopify Creates A Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#create-2020-07
      parameters: []
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_redirects
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/redirects/{redirect_id}.json:
    get:
      summary: Shopify Retrieves A Single Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#show-2020-07
      parameters:
      - in: path
        name: redirect_id
        required: true
        schema:
          type: string
        description: redirect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_redirects_param_redirect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/redirects.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  redirect:
                    path: /ipod
                    target: /pages/itunes
                summary: Create a redirect
              example2:
                value:
                  redirect:
                    path: http://www.apple.com/forums
                    target: http://forums.apple.com
                summary: Create a redirect using a full URL for the path, which will be saved as an absolute path without a domain
              example3:
                value:
                  redirect:
                    body: foobar
                summary: Creating a redirect without a path or target fails and returns an error
      summary: Shopify Creates A Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#create-2020-10
      parameters: []
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: create_redirects
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/redirects/{redirect_id}.json:
    get:
      summary: Shopify Retrieves A Single Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#show-2020-10
      parameters:
      - in: path
        name: redirect_id
        required: true
        schema:
          type: string
        description: redirect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: get_redirects_param_redirect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/redirects.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  redirect:
                    path: /ipod
                    target: /pages/itunes
                summary: Create a redirect
              example2:
                value:
                  redirect:
                    path: http://www.apple.com/forums
                    target: http://forums.apple.com
                summary: Create a redirect using a full URL for the path, which will be saved as an absolute path without a domain
              example3:
                value:
                  redirect:
                    body: foobar
                summary: Creating a redirect without a path or target fails and returns an error
      summary: Shopify Creates A Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#create-2021-01
      parameters: []
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_redirects
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/redirects/{redirect_id}.json:
    get:
      summary: Shopify Retrieves A Single Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#show-2021-01
      parameters:
      - in: path
        name: redirect_id
        required: true
        schema:
          type: string
        description: redirect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_redirects_param_redirect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/redirects.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  redirect:
                    path: /ipod
                    target: /pages/itunes
                summary: Create a redirect
              example2:
                value:
                  redirect:
                    path: http://www.apple.com/forums
                    target: http://forums.apple.com
                summary: Create a redirect using a full URL for the path, which will be saved as an absolute path without a domain
              example3:
                value:
                  redirect:
                    body: foobar
                summary: Creating a redirect without a path or target fails and returns an error
      summary: Shopify Creates A Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#create-unstable
      parameters: []
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_redirects
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/redirects/{redirect_id}.json:
    get:
      summary: Shopify Retrieves A Single Redirect
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/redirect#show-unstable
      parameters:
      - in: path
        name: redirect_id
        required: true
        schema:
          type: string
        description: redirect_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Redirect
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_redirects_param_redirect_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
