openapi: 3.2.0
info:
  title: Shopify Active API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Active
paths:
  /admin/api/2020-01/recurring_application_charges/{recurring_application_charge_id}/customize.json:
    put:
      summary: Shopify Updates The Capped Amount Of An Active Recurring Application Charge
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#customize-2020-01
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      - in: query
        name: recurring_application_charge[capped_amount]
        schema:
          type: integer
        description: recurring_application_charge[capped_amount]
        required: false
      tags:
      - Active
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_update_recurring_application_charges_param_recurring_application_charge_id_customize
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/recurring_application_charges/{recurring_application_charge_id}/customize.json:
    put:
      summary: Shopify Updates The Capped Amount Of An Active Recurring Application Charge
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#customize-2020-04
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      - in: query
        name: recurring_application_charge[capped_amount]
        schema:
          type: integer
        description: recurring_application_charge[capped_amount]
        required: false
      tags:
      - Active
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_update_recurring_application_charges_param_recurring_application_charge_id_customize
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/recurring_application_charges/{recurring_application_charge_id}/customize.json:
    put:
      summary: Shopify Updates The Capped Amount Of An Active Recurring Application Charge
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#customize-2020-07
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      - in: query
        name: recurring_application_charge[capped_amount]
        schema:
          type: integer
        description: recurring_application_charge[capped_amount]
        required: false
      tags:
      - Active
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_update_recurring_application_charges_param_recurring_application_charge_id_customize
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/recurring_application_charges/{recurring_application_charge_id}/customize.json:
    put:
      summary: Shopify Updates The Capped Amount Of An Active Recurring Application Charge
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#customize-2020-10
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      - in: query
        name: recurring_application_charge[capped_amount]
        schema:
          type: integer
        description: recurring_application_charge[capped_amount]
        required: false
      tags:
      - Active
      responses:
        '200':
          description: ''
      operationId: update_recurring_application_charges_param_recurring_application_charge_id_customize
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/recurring_application_charges/{recurring_application_charge_id}/customize.json:
    put:
      summary: Shopify Updates The Capped Amount Of An Active Recurring Application Charge
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#customize-2021-01
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      - in: query
        name: recurring_application_charge[capped_amount]
        schema:
          type: integer
        description: recurring_application_charge[capped_amount]
        required: false
      tags:
      - Active
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_update_recurring_application_charges_param_recurring_application_charge_id_customize
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/recurring_application_charges/{recurring_application_charge_id}/customize.json:
    put:
      summary: Shopify Updates The Capped Amount Of An Active Recurring Application Charge
      description: https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge#customize-unstable
      parameters:
      - in: path
        name: recurring_application_charge_id
        required: true
        schema:
          type: string
        description: recurring_application_charge_id
      - in: query
        name: recurring_application_charge[capped_amount]
        schema:
          type: integer
        description: recurring_application_charge[capped_amount]
        required: false
      tags:
      - Active
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_update_recurring_application_charges_param_recurring_application_charge_id_customize
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
