openapi: 3.2.0
info:
  title: Shopify Currencies API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Currencies
paths:
  /admin/api/2020-01/currencies.json:
    get:
      summary: Shopify Retrieves A List Of Currencies Enabled On A Shop
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/currency#index-2020-01
      parameters: []
      tags:
      - Currencies
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_currencies
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/currencies.json:
    get:
      summary: Shopify Retrieves A List Of Currencies Enabled On A Shop
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/currency#index-2020-04
      parameters: []
      tags:
      - Currencies
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_currencies
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/currencies.json:
    get:
      summary: Shopify Retrieves A List Of Currencies Enabled On A Shop
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/currency#index-2020-07
      parameters: []
      tags:
      - Currencies
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_currencies
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/currencies.json:
    get:
      summary: Shopify Retrieves A List Of Currencies Enabled On A Shop
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/currency#index-2020-10
      parameters: []
      tags:
      - Currencies
      responses:
        '200':
          description: ''
      operationId: get_currencies
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/currencies.json:
    get:
      summary: Shopify Retrieves A List Of Currencies Enabled On A Shop
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/currency#index-2021-01
      parameters: []
      tags:
      - Currencies
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_currencies
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/currencies.json:
    get:
      summary: Shopify Retrieves A List Of Currencies Enabled On A Shop
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/currency#index-unstable
      parameters: []
      tags:
      - Currencies
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_currencies
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
