openapi: 3.2.0
info:
  title: Shopify Dispute API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Dispute
paths:
  /admin/api/2020-01/shopify_payments/disputes/{dispute_id}.json:
    get:
      summary: Shopify Retrieves A Single Dispute By Id
      description: https://shopify.dev/docs/admin-api/rest/reference/shopify_payments/dispute#show-2020-01
      parameters:
      - in: path
        name: dispute_id
        required: true
        schema:
          type: string
        description: dispute_id
      tags:
      - Dispute
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_shopify_payments_disputes_param_dispute_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
