openapi: 3.1.0
info:
  title: Shopify Admin REST About Zip API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Zip
paths:
  /admin/api/2020-01/themes.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  theme:
                    name: Lemongrass
                    src: http://themes.shopify.com/theme.zip
                    role: main
                summary: Create a theme that has a custom name and is published
              example2:
                value:
                  theme:
                    body: foobar
                summary: Creating a theme without a name fails and returns an error
      summary: Shopify Creates A Theme By Providing The Public Url Of A Zip File That Contains The Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#create-2020-01
      parameters: []
      tags:
      - Zip
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_themes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/themes.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  theme:
                    name: Lemongrass
                    src: http://themes.shopify.com/theme.zip
                    role: main
                summary: Create a theme that has a custom name and is published
              example2:
                value:
                  theme:
                    body: foobar
                summary: Creating a theme without a name fails and returns an error
      summary: Shopify Creates A Theme By Providing The Public Url Of A Zip File That Contains The Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#create-2020-04
      parameters: []
      tags:
      - Zip
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_themes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/themes.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  theme:
                    name: Lemongrass
                    src: http://themes.shopify.com/theme.zip
                    role: main
                summary: Create a theme that has a custom name and is published
              example2:
                value:
                  theme:
                    body: foobar
                summary: Creating a theme without a name fails and returns an error
      summary: Shopify Creates A Theme By Providing The Public Url Of A Zip File That Contains The Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#create-2020-07
      parameters: []
      tags:
      - Zip
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_themes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/themes.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  theme:
                    name: Lemongrass
                    src: http://themes.shopify.com/theme.zip
                    role: main
                summary: Create a theme that has a custom name and is published
              example2:
                value:
                  theme:
                    body: foobar
                summary: Creating a theme without a name fails and returns an error
      summary: Shopify Creates A Theme By Providing The Public Url Of A Zip File That Contains The Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#create-2020-10
      parameters: []
      tags:
      - Zip
      responses:
        '200':
          description: ''
      operationId: create_themes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/themes.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  theme:
                    name: Lemongrass
                    src: http://themes.shopify.com/theme.zip
                    role: main
                summary: Create a theme that has a custom name and is published
              example2:
                value:
                  theme:
                    body: foobar
                summary: Creating a theme without a name fails and returns an error
      summary: Shopify Creates A Theme By Providing The Public Url Of A Zip File That Contains The Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#create-2021-01
      parameters: []
      tags:
      - Zip
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_themes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/themes.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  theme:
                    name: Lemongrass
                    src: http://themes.shopify.com/theme.zip
                    role: main
                summary: Create a theme that has a custom name and is published
              example2:
                value:
                  theme:
                    body: foobar
                summary: Creating a theme without a name fails and returns an error
      summary: Shopify Creates A Theme By Providing The Public Url Of A Zip File That Contains The Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#create-unstable
      parameters: []
      tags:
      - Zip
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_themes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
