openapi: 3.2.0
info:
  title: Shopify Account API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Account
paths:
  /admin/api/2020-01/customers/{customer_id}/account_activation_url.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Creating an account activation URL for an enabled customer fails and returns an error
              example2:
                value: {}
                summary: Create an account activation URL for an invited or disabled customer
      summary: Shopify Generate An Account Activation Url For A Customer Whose Account Is Not…
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#account_activation_url-2020-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_customers_param_customer_id_account_activation_url
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/customers/{customer_id}/account_activation_url.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Creating an account activation URL for an enabled customer fails and returns an error
              example2:
                value: {}
                summary: Create an account activation URL for an invited or disabled customer
      summary: Shopify Generate An Account Activation Url For A Customer Whose Account Is Not…
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#account_activation_url-2020-04
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_customers_param_customer_id_account_activation_url
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-04
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/customers/{customer_id}/account_activation_url.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Creating an account activation URL for an enabled customer fails and returns an error
              example2:
                value: {}
                summary: Create an account activation URL for an invited or disabled customer
      summary: Shopify Generate An Account Activation Url For A Customer Whose Account Is Not…
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#account_activation_url-2020-07
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_customers_param_customer_id_account_activation_url
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-07
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/customers/{customer_id}/account_activation_url.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Creating an account activation URL for an enabled customer fails and returns an error
              example2:
                value: {}
                summary: Create an account activation URL for an invited or disabled customer
      summary: Shopify Generate An Account Activation Url For A Customer Whose Account Is Not…
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#account_activation_url-2020-10
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: create_customers_param_customer_id_account_activation_url
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-10
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/customers/{customer_id}/account_activation_url.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Creating an account activation URL for an enabled customer fails and returns an error
              example2:
                value: {}
                summary: Create an account activation URL for an invited or disabled customer
      summary: Shopify Generate An Account Activation Url For A Customer Whose Account Is Not…
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#account_activation_url-2021-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_customers_param_customer_id_account_activation_url
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2021-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/customers/{customer_id}/account_activation_url.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Creating an account activation URL for an enabled customer fails and returns an error
              example2:
                value: {}
                summary: Create an account activation URL for an invited or disabled customer
      summary: Shopify Generate An Account Activation Url For A Customer Whose Account Is Not…
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#account_activation_url-unstable
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_customers_param_customer_id_account_activation_url
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-unstable
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Account
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
