openapi: 3.2.0
info:
  title: Shopify About API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: About
paths:
  /admin/api/2020-01/users/current.json:
    get:
      summary: Shopify Retrieves Information About The User Account Associated With The Access…
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#current-2020-01
      parameters: []
      tags:
      - About
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_users_current
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/users/current.json:
    get:
      summary: Shopify Retrieves Information About The User Account Associated With The Access…
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#current-2020-04
      parameters: []
      tags:
      - About
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_users_current
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/users/current.json:
    get:
      summary: Shopify Retrieves Information About The User Account Associated With The Access…
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#current-2020-07
      parameters: []
      tags:
      - About
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_users_current
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/users/current.json:
    get:
      summary: Shopify Retrieves Information About The User Account Associated With The Access…
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#current-2020-10
      parameters: []
      tags:
      - About
      responses:
        '200':
          description: ''
      operationId: get_users_current
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/users/current.json:
    get:
      summary: Shopify Retrieves Information About The User Account Associated With The Access…
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#current-2021-01
      parameters: []
      tags:
      - About
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_users_current
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/users/current.json:
    get:
      summary: Shopify Retrieves Information About The User Account Associated With The Access…
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#current-unstable
      parameters: []
      tags:
      - About
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_users_current
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
