openapi: 3.2.0
info:
  title: Shopify Retrieves API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Retrieves
paths:
  /admin/api/2020-01/webhooks/{webhook_id}.json:
    get:
      summary: Shopify Retrieves A Single Webhook Subscription
      description: https://shopify.dev/docs/admin-api/rest/reference/events/webhook#show-2020-01
      parameters:
      - in: path
        name: webhook_id
        required: true
        schema:
          type: string
        description: webhook_id
      - in: query
        name: fields
        description: Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_webhooks_param_webhook_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/webhooks/{webhook_id}.json:
    get:
      summary: Shopify Retrieves A Single Webhook Subscription
      description: https://shopify.dev/docs/admin-api/rest/reference/events/webhook#show-2020-04
      parameters:
      - in: path
        name: webhook_id
        required: true
        schema:
          type: string
        description: webhook_id
      - in: query
        name: fields
        description: Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_webhooks_param_webhook_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/webhooks/{webhook_id}.json:
    get:
      summary: Shopify Retrieves A Single Webhook Subscription
      description: https://shopify.dev/docs/admin-api/rest/reference/events/webhook#show-2020-07
      parameters:
      - in: path
        name: webhook_id
        required: true
        schema:
          type: string
        description: webhook_id
      - in: query
        name: fields
        description: Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_webhooks_param_webhook_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/webhooks/{webhook_id}.json:
    get:
      summary: Shopify Retrieves A Single Webhook Subscription
      description: https://shopify.dev/docs/admin-api/rest/reference/events/webhook#show-2020-10
      parameters:
      - in: path
        name: webhook_id
        required: true
        schema:
          type: string
        description: webhook_id
      - in: query
        name: fields
        description: Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: get_webhooks_param_webhook_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/webhooks/{webhook_id}.json:
    get:
      summary: Shopify Retrieves A Single Webhook Subscription
      description: https://shopify.dev/docs/admin-api/rest/reference/events/webhook#show-2021-01
      parameters:
      - in: path
        name: webhook_id
        required: true
        schema:
          type: string
        description: webhook_id
      - in: query
        name: fields
        description: Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_webhooks_param_webhook_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/webhooks/{webhook_id}.json:
    get:
      summary: Shopify Retrieves A Single Webhook Subscription
      description: https://shopify.dev/docs/admin-api/rest/reference/events/webhook#show-unstable
      parameters:
      - in: path
        name: webhook_id
        required: true
        schema:
          type: string
        description: webhook_id
      - in: query
        name: fields
        description: Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_webhooks_param_webhook_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/script_tags/{script_tag_id}.json:
    get:
      summary: Shopify Retrieves A Single Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#show-2020-01
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      - in: query
        name: fields
        description: A comma-separated list of fields to include in the response.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/script_tags/{script_tag_id}.json:
    get:
      summary: Shopify Retrieves A Single Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#show-2020-04
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      - in: query
        name: fields
        description: A comma-separated list of fields to include in the response.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/script_tags/{script_tag_id}.json:
    get:
      summary: Shopify Retrieves A Single Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#show-2020-07
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      - in: query
        name: fields
        description: A comma-separated list of fields to include in the response.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/script_tags/{script_tag_id}.json:
    get:
      summary: Shopify Retrieves A Single Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#show-2020-10
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      - in: query
        name: fields
        description: A comma-separated list of fields to include in the response.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: get_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/script_tags/{script_tag_id}.json:
    get:
      summary: Shopify Retrieves A Single Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#show-2021-01
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      - in: query
        name: fields
        description: A comma-separated list of fields to include in the response.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/script_tags/{script_tag_id}.json:
    get:
      summary: Shopify Retrieves A Single Script Tag
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/scripttag#show-unstable
      parameters:
      - in: path
        name: script_tag_id
        required: true
        schema:
          type: string
        description: script_tag_id
      - in: query
        name: fields
        description: A comma-separated list of fields to include in the response.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_script_tags_param_script_tag_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/themes/{theme_id}.json:
    get:
      summary: Shopify Retrieves A Single Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#show-2020-01
      parameters:
      - in: path
        name: theme_id
        required: true
        schema:
          type: string
        description: theme_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_themes_param_theme_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/themes/{theme_id}.json:
    get:
      summary: Shopify Retrieves A Single Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#show-2020-04
      parameters:
      - in: path
        name: theme_id
        required: true
        schema:
          type: string
        description: theme_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_themes_param_theme_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/themes/{theme_id}.json:
    get:
      summary: Shopify Retrieves A Single Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#show-2020-07
      parameters:
      - in: path
        name: theme_id
        required: true
        schema:
          type: string
        description: theme_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_themes_param_theme_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/themes/{theme_id}.json:
    get:
      summary: Shopify Retrieves A Single Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#show-2020-10
      parameters:
      - in: path
        name: theme_id
        required: true
        schema:
          type: string
        description: theme_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: get_themes_param_theme_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/themes/{theme_id}.json:
    get:
      summary: Shopify Retrieves A Single Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#show-2021-01
      parameters:
      - in: path
        name: theme_id
        required: true
        schema:
          type: string
        description: theme_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_themes_param_theme_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/themes/{theme_id}.json:
    get:
      summary: Shopify Retrieves A Single Theme
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/theme#show-unstable
      parameters:
      - in: path
        name: theme_id
        required: true
        schema:
          type: string
        description: theme_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_themes_param_theme_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/users/{user_id}.json:
    get:
      summary: Shopify Retrieves A Single User
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#show-2020-01
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
        description: user_id
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_users_param_user_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/users/{user_id}.json:
    get:
      summary: Shopify Retrieves A Single User
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#show-2020-04
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
        description: user_id
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_users_param_user_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/users/{user_id}.json:
    get:
      summary: Shopify Retrieves A Single User
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#show-2020-07
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
        description: user_id
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_users_param_user_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/users/{user_id}.json:
    get:
      summary: Shopify Retrieves A Single User
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#show-2020-10
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
        description: user_id
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: get_users_param_user_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/users/{user_id}.json:
    get:
      summary: Shopify Retrieves A Single User
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#show-2021-01
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
        description: user_id
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_users_param_user_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/users/{user_id}.json:
    get:
      summary: Shopify Retrieves A Single User
      description: https://shopify.dev/docs/admin-api/rest/reference/plus/user#show-unstable
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          type: string
        description: user_id
      tags:
      - Retrieves
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_users_param_user_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
