openapi: 3.1.0
info:
  title: Shopify Admin REST About Invites API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Invites
paths:
  /admin/api/2020-01/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Invites
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-04
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Invites
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-07
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Invites
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2020-10
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Invites
      responses:
        '200':
          description: ''
      operationId: create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-2021-01
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Invites
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/customers/{customer_id}/send_invite.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  customer_invite: {}
                summary: Send the default invite
              example2:
                value:
                  customer_invite:
                    to: new_test_email@shopify.com
                    from: noaccesssteve@jobs.com
                    bcc:
                    - noaccesssteve@jobs.com
                    subject: Welcome to my new shop
                    custom_message: My awesome new store
                summary: Send a customized invite
      summary: Shopify Sends An Account Invite To A Customer
      description: https://shopify.dev/docs/admin-api/rest/reference/customers/customer#send_invite-unstable
      parameters:
      - in: path
        name: customer_id
        required: true
        schema:
          type: string
        description: customer_id
      tags:
      - Invites
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_customers_param_customer_id_send_invite
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
