openapi: 3.1.0
info:
  title: Shopify REST About Admin API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Admin
paths:
  /admin/api/2020-01/metafields/{metafield_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  metafield:
                    id: 721389482
                    value: something new
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
              example2:
                value:
                  metafield:
                    id: 845366454
                    value: titre
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
      summary: Shopify Updates A Metafield
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#update-2020-01
      parameters:
      - in: path
        name: metafield_id
        required: true
        schema:
          type: string
        description: metafield_id
      tags:
      - Admin
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_update_metafields_param_metafield_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/metafields/{metafield_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  metafield:
                    id: 721389482
                    value: something new
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
              example2:
                value:
                  metafield:
                    id: 845366454
                    value: titre
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
      summary: Shopify Updates A Metafield
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#update-2020-04
      parameters:
      - in: path
        name: metafield_id
        required: true
        schema:
          type: string
        description: metafield_id
      tags:
      - Admin
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_update_metafields_param_metafield_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/metafields/{metafield_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  metafield:
                    id: 721389482
                    value: something new
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
              example2:
                value:
                  metafield:
                    id: 845366454
                    value: titre
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
      summary: Shopify Updates A Metafield
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#update-2020-07
      parameters:
      - in: path
        name: metafield_id
        required: true
        schema:
          type: string
        description: metafield_id
      tags:
      - Admin
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_update_metafields_param_metafield_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/metafields/{metafield_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  metafield:
                    id: 721389482
                    value: something new
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
              example2:
                value:
                  metafield:
                    id: 845366454
                    value: titre
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
      summary: Shopify Updates A Metafield
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#update-2020-10
      parameters:
      - in: path
        name: metafield_id
        required: true
        schema:
          type: string
        description: metafield_id
      tags:
      - Admin
      responses:
        '200':
          description: ''
      operationId: update_metafields_param_metafield_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/metafields/{metafield_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  metafield:
                    id: 721389482
                    value: something new
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
              example2:
                value:
                  metafield:
                    id: 845366454
                    value: titre
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
      summary: Shopify Updates A Metafield
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#update-2021-01
      parameters:
      - in: path
        name: metafield_id
        required: true
        schema:
          type: string
        description: metafield_id
      tags:
      - Admin
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_update_metafields_param_metafield_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/metafields/{metafield_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  metafield:
                    id: 721389482
                    value: something new
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
              example2:
                value:
                  metafield:
                    id: 845366454
                    value: titre
                    value_type: string
                summary: Update a metafield. The namespace and key of an existing metafield can't be changed.
      summary: Shopify Updates A Metafield
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#update-unstable
      parameters:
      - in: path
        name: metafield_id
        required: true
        schema:
          type: string
        description: metafield_id
      tags:
      - Admin
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_update_metafields_param_metafield_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
