openapi: 3.2.0
info:
  title: Shopify Cancels API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Cancels
paths:
  /admin/api/2020-01/fulfillments/{fulfillment_id}/cancel.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Cancel a fulfillment
      summary: Shopify Cancels A Fulfillment
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#cancelV2-2020-01
      parameters:
      - in: path
        name: fulfillment_id
        required: true
        schema:
          type: string
        description: fulfillment_id
      tags:
      - Cancels
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_fulfillments_param_fulfillment_id_cancel
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/fulfillments/{fulfillment_id}/cancel.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Cancel a fulfillment
      summary: Shopify Cancels A Fulfillment
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#cancelV2-2020-04
      parameters:
      - in: path
        name: fulfillment_id
        required: true
        schema:
          type: string
        description: fulfillment_id
      tags:
      - Cancels
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_fulfillments_param_fulfillment_id_cancel
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/fulfillments/{fulfillment_id}/cancel.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Cancel a fulfillment
      summary: Shopify Cancels A Fulfillment
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#cancelV2-2020-07
      parameters:
      - in: path
        name: fulfillment_id
        required: true
        schema:
          type: string
        description: fulfillment_id
      tags:
      - Cancels
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_fulfillments_param_fulfillment_id_cancel
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/fulfillments/{fulfillment_id}/cancel.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Cancel a fulfillment
      summary: Shopify Cancels A Fulfillment
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#cancelV2-2020-10
      parameters:
      - in: path
        name: fulfillment_id
        required: true
        schema:
          type: string
        description: fulfillment_id
      tags:
      - Cancels
      responses:
        '200':
          description: ''
      operationId: create_fulfillments_param_fulfillment_id_cancel
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/fulfillments/{fulfillment_id}/cancel.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Cancel a fulfillment
      summary: Shopify Cancels A Fulfillment
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#cancelV2-2021-01
      parameters:
      - in: path
        name: fulfillment_id
        required: true
        schema:
          type: string
        description: fulfillment_id
      tags:
      - Cancels
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_fulfillments_param_fulfillment_id_cancel
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/fulfillments/{fulfillment_id}/cancel.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value: {}
                summary: Cancel a fulfillment
      summary: Shopify Cancels A Fulfillment
      description: https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#cancelV2-unstable
      parameters:
      - in: path
        name: fulfillment_id
        required: true
        schema:
          type: string
        description: fulfillment_id
      tags:
      - Cancels
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_fulfillments_param_fulfillment_id_cancel
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
