openapi: 3.2.0
info:
  title: Shopify Blog API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Blog
paths:
  /admin/api/2020-01/blogs.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  blog:
                    title: Apple main blog
                summary: Create a new empty blog
              example2:
                value:
                  blog:
                    body: foobar
                summary: Trying to create a blog without a title will return an error
              example3:
                value:
                  blog:
                    title: Apple main blog
                    metafields:
                    - key: new
                      value: newvalue
                      value_type: string
                      namespace: global
                summary: Create a new empty blog with a metafield
      summary: Shopify Create A New Blog
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/blog#create-2020-01
      parameters: []
      tags:
      - Blog
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_blogs
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/blogs/{blog_id}.json:
    get:
      summary: Shopify Get A Single Blog By Its Id
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/blog#show-2020-01
      parameters:
      - in: path
        name: blog_id
        required: true
        schema:
          type: string
        description: blog_id
      - in: query
        name: fields
        description: comma-separated list of fields to include in the response
        schema: {}
        required: false
      tags:
      - Blog
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_blogs_param_blog_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  blog:
                    id: 241253187
                    title: IPod Updates
                summary: Update an existing blog title
              example2:
                value:
                  blog:
                    id: 241253187
                    title: IPod Updates
                    handle: ipod-updates
                    commentable: moderate
                summary: Update an existing blog title and handle and also activate comments
              example3:
                value:
                  blog:
                    id: 241253187
                    metafields:
                    - key: new
                      value: newvalue
                      value_type: string
                      namespace: global
                summary: Add a metafield to an existing blog
      summary: Shopify Update A Blog
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/blog#update-2020-01
      parameters:
      - in: path
        name: blog_id
        required: true
        schema:
          type: string
        description: blog_id
      tags:
      - Blog
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_update_blogs_param_blog_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
    delete:
      summary: Shopify Delete A Blog
      description: https://shopify.dev/docs/admin-api/rest/reference/online-store/blog#destroy-2020-01
      parameters:
      - in: path
        name: blog_id
        required: true
        schema:
          type: string
        description: blog_id
      tags:
      - Blog
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_delete_blogs_param_blog_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
