openapi: 3.2.0
info:
  title: Shopify Connects API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Connects
paths:
  /admin/api/2020-01/inventory_levels/connect.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connect an inventory item to a location
              example2:
                value:
                  location_id: 123
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a non-existent location fails and returns an error
              example3:
                value:
                  location_id: 48752903
                  inventory_item_id: 808950810
                summary: 'Connecting an inventory item to a fulfillment service location without "relocate_if_necessary": true fails with a 422 error'
              example4:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a location when the store hasn't enabled multiple locations fails with a 403 error
      summary: Shopify Connects An Inventory Item To A Location By Creating An Inventory Level…
      description: https://shopify.dev/docs/admin-api/rest/reference/inventory/inventorylevel#connect-2020-01
      parameters:
      - in: query
        name: "inventory_item_id\n                  required"
        description: The ID of the inventory item.
        schema: {}
        required: false
      - in: query
        name: "location_id\n                  required"
        description: The ID of the location that the inventory level belongs to. To find the ID of the location, use the Location resource.
        schema: {}
        required: false
      - in: query
        name: relocate_if_necessary
        description: "Whether inventory for any previously connected locations will be relocated. This property is ignored when no fulfillment service location is involved. For more information, see Inventory levels and fulfillment service locations.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Connects
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_inventory_levels_connect
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/inventory_levels/connect.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connect an inventory item to a location
              example2:
                value:
                  location_id: 123
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a non-existent location fails and returns an error
              example3:
                value:
                  location_id: 48752903
                  inventory_item_id: 808950810
                summary: 'Connecting an inventory item to a fulfillment service location without "relocate_if_necessary": true fails with a 422 error'
              example4:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a location when the store hasn't enabled multiple locations fails with a 403 error
      summary: Shopify Connects An Inventory Item To A Location By Creating An Inventory Level…
      description: https://shopify.dev/docs/admin-api/rest/reference/inventory/inventorylevel#connect-2020-04
      parameters:
      - in: query
        name: "inventory_item_id\n                  required"
        description: The ID of the inventory item.
        schema: {}
        required: false
      - in: query
        name: "location_id\n                  required"
        description: The ID of the location that the inventory level belongs to. To find the ID of the location, use the Location resource.
        schema: {}
        required: false
      - in: query
        name: relocate_if_necessary
        description: "Whether inventory for any previously connected locations will be relocated. This property is ignored when no fulfillment service location is involved. For more information, see Inventory levels and fulfillment service locations.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Connects
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_inventory_levels_connect
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/inventory_levels/connect.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connect an inventory item to a location
              example2:
                value:
                  location_id: 123
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a non-existent location fails and returns an error
              example3:
                value:
                  location_id: 48752903
                  inventory_item_id: 808950810
                summary: 'Connecting an inventory item to a fulfillment service location without "relocate_if_necessary": true fails with a 422 error'
              example4:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a location when the store hasn't enabled multiple locations fails with a 403 error
      summary: Shopify Connects An Inventory Item To A Location By Creating An Inventory Level…
      description: https://shopify.dev/docs/admin-api/rest/reference/inventory/inventorylevel#connect-2020-07
      parameters:
      - in: query
        name: "inventory_item_id\n                  required"
        description: The ID of the inventory item.
        schema: {}
        required: false
      - in: query
        name: "location_id\n                  required"
        description: The ID of the location that the inventory level belongs to. To find the ID of the location, use the Location resource.
        schema: {}
        required: false
      - in: query
        name: relocate_if_necessary
        description: "Whether inventory for any previously connected locations will be relocated. This property is ignored when no fulfillment service location is involved. For more information, see Inventory levels and fulfillment service locations.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Connects
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_inventory_levels_connect
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/inventory_levels/connect.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connect an inventory item to a location
              example2:
                value:
                  location_id: 123
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a non-existent location fails and returns an error
              example3:
                value:
                  location_id: 48752903
                  inventory_item_id: 808950810
                summary: 'Connecting an inventory item to a fulfillment service location without "relocate_if_necessary": true fails with a 422 error'
              example4:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a location when the store hasn't enabled multiple locations fails with a 403 error
      summary: Shopify Connects An Inventory Item To A Location By Creating An Inventory Level…
      description: https://shopify.dev/docs/admin-api/rest/reference/inventory/inventorylevel#connect-2020-10
      parameters:
      - in: query
        name: "inventory_item_id\n                  required"
        description: The ID of the inventory item.
        schema: {}
        required: false
      - in: query
        name: "location_id\n                  required"
        description: The ID of the location that the inventory level belongs to. To find the ID of the location, use the Location resource.
        schema: {}
        required: false
      - in: query
        name: relocate_if_necessary
        description: "Whether inventory for any previously connected locations will be relocated. This property is ignored when no fulfillment service location is involved. For more information, see Inventory levels and fulfillment service locations.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Connects
      responses:
        '200':
          description: ''
      operationId: create_inventory_levels_connect
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/inventory_levels/connect.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connect an inventory item to a location
              example2:
                value:
                  location_id: 123
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a non-existent location fails and returns an error
              example3:
                value:
                  location_id: 48752903
                  inventory_item_id: 808950810
                summary: 'Connecting an inventory item to a fulfillment service location without "relocate_if_necessary": true fails with a 422 error'
              example4:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a location when the store hasn't enabled multiple locations fails with a 403 error
      summary: Shopify Connects An Inventory Item To A Location By Creating An Inventory Level…
      description: https://shopify.dev/docs/admin-api/rest/reference/inventory/inventorylevel#connect-2021-01
      parameters:
      - in: query
        name: "inventory_item_id\n                  required"
        description: The ID of the inventory item.
        schema: {}
        required: false
      - in: query
        name: "location_id\n                  required"
        description: The ID of the location that the inventory level belongs to. To find the ID of the location, use the Location resource.
        schema: {}
        required: false
      - in: query
        name: relocate_if_necessary
        description: "Whether inventory for any previously connected locations will be relocated. This property is ignored when no fulfillment service location is involved. For more information, see Inventory levels and fulfillment service locations.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Connects
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_inventory_levels_connect
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/inventory_levels/connect.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connect an inventory item to a location
              example2:
                value:
                  location_id: 123
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a non-existent location fails and returns an error
              example3:
                value:
                  location_id: 48752903
                  inventory_item_id: 808950810
                summary: 'Connecting an inventory item to a fulfillment service location without "relocate_if_necessary": true fails with a 422 error'
              example4:
                value:
                  location_id: 192722535
                  inventory_item_id: 457924702
                summary: Connecting an inventory item to a location when the store hasn't enabled multiple locations fails with a 403 error
      summary: Shopify Connects An Inventory Item To A Location By Creating An Inventory Level…
      description: https://shopify.dev/docs/admin-api/rest/reference/inventory/inventorylevel#connect-unstable
      parameters:
      - in: query
        name: "inventory_item_id\n                  required"
        description: The ID of the inventory item.
        schema: {}
        required: false
      - in: query
        name: "location_id\n                  required"
        description: The ID of the location that the inventory level belongs to. To find the ID of the location, use the Location resource.
        schema: {}
        required: false
      - in: query
        name: relocate_if_necessary
        description: "Whether inventory for any previously connected locations will be relocated. This property is ignored when no fulfillment service location is involved. For more information, see Inventory levels and fulfillment service locations.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Connects
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_inventory_levels_connect
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
