openapi: 3.2.0
info:
  title: Shopify Versions API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Versions
paths:
  /admin/api/2020-01/countries.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    code: FR
                summary: Create a country using Shopify's tax rate for it
              example2:
                value:
                  country:
                    code: FR
                    tax: 0.2
                summary: Create a country using a custom tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#create-2020-01
      parameters: []
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_create_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/countries/{country_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    id: 879921427
                    tax: 0.05
                summary: Update a country's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#update-2020-01
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_update_countries_param_country_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/countries.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    code: FR
                summary: Create a country using Shopify's tax rate for it
              example2:
                value:
                  country:
                    code: FR
                    tax: 0.2
                summary: Create a country using a custom tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#create-2020-04
      parameters: []
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_create_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/countries/{country_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    id: 879921427
                    tax: 0.05
                summary: Update a country's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#update-2020-04
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_update_countries_param_country_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/countries.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    code: FR
                summary: Create a country using Shopify's tax rate for it
              example2:
                value:
                  country:
                    code: FR
                    tax: 0.2
                summary: Create a country using a custom tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#create-2020-07
      parameters: []
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_create_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/countries/{country_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    id: 879921427
                    tax: 0.05
                summary: Update a country's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#update-2020-07
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_update_countries_param_country_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/countries.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    code: FR
                summary: Create a country using Shopify's tax rate for it
              example2:
                value:
                  country:
                    code: FR
                    tax: 0.2
                summary: Create a country using a custom tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#create-2020-10
      parameters: []
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: create_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/countries/{country_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    id: 879921427
                    tax: 0.05
                summary: Update a country's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#update-2020-10
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: update_countries_param_country_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/countries.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    code: FR
                summary: Create a country using Shopify's tax rate for it
              example2:
                value:
                  country:
                    code: FR
                    tax: 0.2
                summary: Create a country using a custom tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#create-2021-01
      parameters: []
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_create_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/countries/{country_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    id: 879921427
                    tax: 0.05
                summary: Update a country's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#update-2021-01
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_update_countries_param_country_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/countries.json:
    post:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    code: FR
                summary: Create a country using Shopify's tax rate for it
              example2:
                value:
                  country:
                    code: FR
                    tax: 0.2
                summary: Create a country using a custom tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#create-unstable
      parameters: []
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_create_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/countries/{country_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  country:
                    id: 879921427
                    tax: 0.05
                summary: Update a country's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#update-unstable
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_update_countries_param_country_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/countries/{country_id}/provinces/{province_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  province:
                    id: 224293623
                    tax: 0.09
                summary: Update a province's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/province#update-2020-01
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      - in: path
        name: province_id
        required: true
        schema:
          type: string
        description: province_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_update_countries_param_country_id_provinces_param_province_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/countries/{country_id}/provinces/{province_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  province:
                    id: 224293623
                    tax: 0.09
                summary: Update a province's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/province#update-2020-04
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      - in: path
        name: province_id
        required: true
        schema:
          type: string
        description: province_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_update_countries_param_country_id_provinces_param_province_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/countries/{country_id}/provinces/{province_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  province:
                    id: 224293623
                    tax: 0.09
                summary: Update a province's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/province#update-2020-07
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      - in: path
        name: province_id
        required: true
        schema:
          type: string
        description: province_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_update_countries_param_country_id_provinces_param_province_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/countries/{country_id}/provinces/{province_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  province:
                    id: 224293623
                    tax: 0.09
                summary: Update a province's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/province#update-2020-10
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      - in: path
        name: province_id
        required: true
        schema:
          type: string
        description: province_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: update_countries_param_country_id_provinces_param_province_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/countries/{country_id}/provinces/{province_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  province:
                    id: 224293623
                    tax: 0.09
                summary: Update a province's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/province#update-2021-01
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      - in: path
        name: province_id
        required: true
        schema:
          type: string
        description: province_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_update_countries_param_country_id_provinces_param_province_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/countries/{country_id}/provinces/{province_id}.json:
    put:
      requestBody:
        content:
          application/json:
            schema: {}
            examples:
              example1:
                value:
                  province:
                    id: 224293623
                    tax: 0.09
                summary: Update a province's tax rate
      summary: Shopify As Of Version 2020-10
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/province#update-unstable
      parameters:
      - in: path
        name: country_id
        required: true
        schema:
          type: string
        description: country_id
      - in: path
        name: province_id
        required: true
        schema:
          type: string
        description: province_id
      tags:
      - Versions
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_update_countries_param_country_id_provinces_param_province_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
