openapi: 3.2.0
info:
  title: Shopify Discount API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Discount
paths:
  /admin/api/2020-01/price_rules/{price_rule_id}/discount_codes.json:
    get:
      summary: Shopify Retrieve A List Of Discount Codes
      description: https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#index-2020-01
      parameters:
      - in: path
        name: price_rule_id
        required: true
        schema:
          type: string
        description: price_rule_id
      tags:
      - Discount
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_price_rules_param_price_rule_id_discount_codes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/price_rules/{price_rule_id}/discount_codes.json:
    get:
      summary: Shopify Retrieve A List Of Discount Codes
      description: https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#index-2020-04
      parameters:
      - in: path
        name: price_rule_id
        required: true
        schema:
          type: string
        description: price_rule_id
      tags:
      - Discount
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_price_rules_param_price_rule_id_discount_codes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/price_rules/{price_rule_id}/discount_codes.json:
    get:
      summary: Shopify Retrieve A List Of Discount Codes
      description: https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#index-2020-07
      parameters:
      - in: path
        name: price_rule_id
        required: true
        schema:
          type: string
        description: price_rule_id
      tags:
      - Discount
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_price_rules_param_price_rule_id_discount_codes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/price_rules/{price_rule_id}/discount_codes.json:
    get:
      summary: Shopify Retrieve A List Of Discount Codes
      description: https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#index-2020-10
      parameters:
      - in: path
        name: price_rule_id
        required: true
        schema:
          type: string
        description: price_rule_id
      tags:
      - Discount
      responses:
        '200':
          description: ''
      operationId: get_price_rules_param_price_rule_id_discount_codes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/price_rules/{price_rule_id}/discount_codes.json:
    get:
      summary: Shopify Retrieve A List Of Discount Codes
      description: https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#index-2021-01
      parameters:
      - in: path
        name: price_rule_id
        required: true
        schema:
          type: string
        description: price_rule_id
      tags:
      - Discount
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_price_rules_param_price_rule_id_discount_codes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/price_rules/{price_rule_id}/discount_codes.json:
    get:
      summary: Shopify Retrieve A List Of Discount Codes
      description: https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#index-unstable
      parameters:
      - in: path
        name: price_rule_id
        required: true
        schema:
          type: string
        description: price_rule_id
      tags:
      - Discount
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_price_rules_param_price_rule_id_discount_codes
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
