openapi: 3.1.0
info:
  title: Shopify Admin REST About Listings API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Listings
paths:
  /admin/api/2020-01/collection_listings.json:
    get:
      summary: Shopify Retrieve Collection Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/collectionlisting#index-2020-01
      parameters:
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_collection_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/collection_listings.json:
    get:
      summary: Shopify Retrieve Collection Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/collectionlisting#index-2020-04
      parameters:
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_collection_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/collection_listings.json:
    get:
      summary: Shopify Retrieve Collection Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/collectionlisting#index-2020-07
      parameters:
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_collection_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/collection_listings.json:
    get:
      summary: Shopify Retrieve Collection Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/collectionlisting#index-2020-10
      parameters:
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: get_collection_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/collection_listings.json:
    get:
      summary: Shopify Retrieve Collection Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/collectionlisting#index-2021-01
      parameters:
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_collection_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/collection_listings.json:
    get:
      summary: Shopify Retrieve Collection Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/collectionlisting#index-unstable
      parameters:
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_collection_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/product_listings.json:
    get:
      summary: Shopify Retrieve Product Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/productlisting#index-2020-01
      parameters:
      - in: query
        name: product_ids
        description: A comma-separated list of product ids
        schema: {}
        required: false
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      - in: query
        name: collection_id
        description: Filter by products belonging to a particular collection
        schema: {}
        required: false
      - in: query
        name: updated_at_min
        description: Filter by products last updated after a certain date and time (formatted in ISO 8601)
        schema: {}
        required: false
      - in: query
        name: handle
        description: Filter by product handle
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_product_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/product_listings.json:
    get:
      summary: Shopify Retrieve Product Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/productlisting#index-2020-04
      parameters:
      - in: query
        name: product_ids
        description: A comma-separated list of product ids
        schema: {}
        required: false
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      - in: query
        name: collection_id
        description: Filter by products belonging to a particular collection
        schema: {}
        required: false
      - in: query
        name: updated_at_min
        description: Filter by products last updated after a certain date and time (formatted in ISO 8601)
        schema: {}
        required: false
      - in: query
        name: handle
        description: Filter by product handle
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_product_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/product_listings.json:
    get:
      summary: Shopify Retrieve Product Listings That Are Published To Your App
      description: https://shopify.dev/docs/admin-api/rest/reference/sales-channels/productlisting#index-2020-07
      parameters:
      - in: query
        name: product_ids
        description: A comma-separated list of product ids
        schema: {}
        required: false
      - in: query
        name: limit
        description: "Amount of results\n                  (default: 50, maximum: 1000)"
        schema: {}
        required: false
      - in: query
        name: collection_id
        description: Filter by products belonging to a particular collection
        schema: {}
        required: false
      - in: query
        name: updated_at_min
        description: Filter by products last updated after a certain date and time (formatted in ISO 8601)
        schema: {}
        required: false
      - in: query
        name: handle
        description: Filter by product handle
        schema: {}
        required: false
      tags:
      - Listings
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_product_listings
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
