openapi: 3.1.0
info:
  title: Shopify Admin REST About Metafields API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Metafields
paths:
  /admin/api/2020-01/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-01
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-01/metafields/count.json:
    get:
      summary: Shopify Retrieves A Count Of A Resource's Metafields
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#count-2020-01
      parameters: []
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_metafields_count
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-04
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/metafields/count.json:
    get:
      summary: Shopify Retrieves A Count Of A Resource's Metafields
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#count-2020-04
      parameters: []
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_metafields_count
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-07
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/metafields/count.json:
    get:
      summary: Shopify Retrieves A Count Of A Resource's Metafields
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#count-2020-07
      parameters: []
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_metafields_count
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-10
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/metafields/count.json:
    get:
      summary: Shopify Retrieves A Count Of A Resource's Metafields
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#count-2020-10
      parameters: []
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: get_metafields_count
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2021-01
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/metafields/count.json:
    get:
      summary: Shopify Retrieves A Count Of A Resource's Metafields
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#count-2021-01
      parameters: []
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_metafields_count
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-unstable
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/metafields/count.json:
    get:
      summary: Shopify Retrieves A Count Of A Resource's Metafields
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#count-unstable
      parameters: []
      tags:
      - Metafields
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_metafields_count
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
