openapi: 3.2.0
info:
  title: Shopify Refund API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Refund
paths:
  /admin/api/2020-01/orders/{order_id}/refunds/{refund_id}.json:
    get:
      summary: Shopify Retrieves A Specific Refund
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund#show-2020-01
      parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
        description: order_id
      - in: path
        name: refund_id
        required: true
        schema:
          type: string
        description: refund_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      - in: query
        name: in_shop_currency
        description: "Show amounts in the shop currency for the underlying transaction.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Refund
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_orders_param_order_id_refunds_param_refund_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/orders/{order_id}/refunds/{refund_id}.json:
    get:
      summary: Shopify Retrieves A Specific Refund
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund#show-2020-04
      parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
        description: order_id
      - in: path
        name: refund_id
        required: true
        schema:
          type: string
        description: refund_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      - in: query
        name: in_shop_currency
        description: "Show amounts in the shop currency for the underlying transaction.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Refund
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_orders_param_order_id_refunds_param_refund_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/orders/{order_id}/refunds/{refund_id}.json:
    get:
      summary: Shopify Retrieves A Specific Refund
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund#show-2020-07
      parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
        description: order_id
      - in: path
        name: refund_id
        required: true
        schema:
          type: string
        description: refund_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      - in: query
        name: in_shop_currency
        description: "Show amounts in the shop currency for the underlying transaction.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Refund
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_orders_param_order_id_refunds_param_refund_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/orders/{order_id}/refunds/{refund_id}.json:
    get:
      summary: Shopify Retrieves A Specific Refund
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund#show-2020-10
      parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
        description: order_id
      - in: path
        name: refund_id
        required: true
        schema:
          type: string
        description: refund_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      - in: query
        name: in_shop_currency
        description: "Show amounts in the shop currency for the underlying transaction.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Refund
      responses:
        '200':
          description: ''
      operationId: get_orders_param_order_id_refunds_param_refund_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/orders/{order_id}/refunds/{refund_id}.json:
    get:
      summary: Shopify Retrieves A Specific Refund
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund#show-2021-01
      parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
        description: order_id
      - in: path
        name: refund_id
        required: true
        schema:
          type: string
        description: refund_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      - in: query
        name: in_shop_currency
        description: "Show amounts in the shop currency for the underlying transaction.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Refund
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_orders_param_order_id_refunds_param_refund_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/orders/{order_id}/refunds/{refund_id}.json:
    get:
      summary: Shopify Retrieves A Specific Refund
      description: https://shopify.dev/docs/admin-api/rest/reference/orders/refund#show-unstable
      parameters:
      - in: path
        name: order_id
        required: true
        schema:
          type: string
        description: order_id
      - in: path
        name: refund_id
        required: true
        schema:
          type: string
        description: refund_id
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      - in: query
        name: in_shop_currency
        description: "Show amounts in the shop currency for the underlying transaction.\n                  (default: false)"
        schema: {}
        required: false
      tags:
      - Refund
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_orders_param_order_id_refunds_param_refund_id
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
