openapi: 3.1.0
info:
  title: Shopify Admin REST About Tender API
  description: The Shopify Admin REST API lets you build apps and integrations that extend and enhance the Shopify admin. Access products, customers, orders, inventory, fulfillment, and more. Endpoints are organized by resource type and versioned by release date.
  version: 2025-01
  contact:
    name: Shopify
    url: https://shopify.dev/docs/api/admin-rest
    email: api@shopify.com
  license:
    name: Shopify API Terms
    url: https://www.shopify.com/legal/api-terms
  x-date: '2026-03-04'
servers:
- url: https://{store}.myshopify.com/admin/api/2025-01
  description: Shopify Admin REST API
  variables:
    store:
      default: my-store
      description: The Shopify store subdomain
security:
- AccessToken: []
tags:
- name: Tender
paths:
  /admin/api/2020-01/tender_transactions.json:
    get:
      summary: Shopify Retrieves A List Of Tender Transactions
      description: https://shopify.dev/docs/admin-api/rest/reference/tendertransaction#index-2020-01
      parameters:
      - in: query
        name: limit
        description: "The maximum number of results to retrieve.\n                  (default: 50, maximum: 250)"
        schema: {}
        required: false
      - in: query
        name: since_id
        description: Retrieve only transactions after the specified ID.
        schema: {}
        required: false
      - in: query
        name: processed_at_min
        description: Show tender transactions processed_at or after the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at_max
        description: Show tender transactions processed_at or before the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at
        description: Show tender transactions processed at the specified date.
        schema: {}
        required: false
      - in: query
        name: order
        description: Show tender transactions ordered by processed_at in ascending or descending order.
        schema: {}
        required: false
      tags:
      - Tender
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_tender_transactions
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/tender_transactions.json:
    get:
      summary: Shopify Retrieves A List Of Tender Transactions
      description: https://shopify.dev/docs/admin-api/rest/reference/tendertransaction#index-2020-04
      parameters:
      - in: query
        name: limit
        description: "The maximum number of results to retrieve.\n                  (default: 50, maximum: 250)"
        schema: {}
        required: false
      - in: query
        name: since_id
        description: Retrieve only transactions after the specified ID.
        schema: {}
        required: false
      - in: query
        name: processed_at_min
        description: Show tender transactions processed_at or after the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at_max
        description: Show tender transactions processed_at or before the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at
        description: Show tender transactions processed at the specified date.
        schema: {}
        required: false
      - in: query
        name: order
        description: Show tender transactions ordered by processed_at in ascending or descending order.
        schema: {}
        required: false
      tags:
      - Tender
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_tender_transactions
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/tender_transactions.json:
    get:
      summary: Shopify Retrieves A List Of Tender Transactions
      description: https://shopify.dev/docs/admin-api/rest/reference/tendertransaction#index-2020-07
      parameters:
      - in: query
        name: limit
        description: "The maximum number of results to retrieve.\n                  (default: 50, maximum: 250)"
        schema: {}
        required: false
      - in: query
        name: since_id
        description: Retrieve only transactions after the specified ID.
        schema: {}
        required: false
      - in: query
        name: processed_at_min
        description: Show tender transactions processed_at or after the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at_max
        description: Show tender transactions processed_at or before the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at
        description: Show tender transactions processed at the specified date.
        schema: {}
        required: false
      - in: query
        name: order
        description: Show tender transactions ordered by processed_at in ascending or descending order.
        schema: {}
        required: false
      tags:
      - Tender
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_tender_transactions
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/tender_transactions.json:
    get:
      summary: Shopify Retrieves A List Of Tender Transactions
      description: https://shopify.dev/docs/admin-api/rest/reference/tendertransaction#index-2020-10
      parameters:
      - in: query
        name: limit
        description: "The maximum number of results to retrieve.\n                  (default: 50, maximum: 250)"
        schema: {}
        required: false
      - in: query
        name: since_id
        description: Retrieve only transactions after the specified ID.
        schema: {}
        required: false
      - in: query
        name: processed_at_min
        description: Show tender transactions processed_at or after the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at_max
        description: Show tender transactions processed_at or before the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at
        description: Show tender transactions processed at the specified date.
        schema: {}
        required: false
      - in: query
        name: order
        description: Show tender transactions ordered by processed_at in ascending or descending order.
        schema: {}
        required: false
      tags:
      - Tender
      responses:
        '200':
          description: ''
      operationId: get_tender_transactions
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/tender_transactions.json:
    get:
      summary: Shopify Retrieves A List Of Tender Transactions
      description: https://shopify.dev/docs/admin-api/rest/reference/tendertransaction#index-2021-01
      parameters:
      - in: query
        name: limit
        description: "The maximum number of results to retrieve.\n                  (default: 50, maximum: 250)"
        schema: {}
        required: false
      - in: query
        name: since_id
        description: Retrieve only transactions after the specified ID.
        schema: {}
        required: false
      - in: query
        name: processed_at_min
        description: Show tender transactions processed_at or after the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at_max
        description: Show tender transactions processed_at or before the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at
        description: Show tender transactions processed at the specified date.
        schema: {}
        required: false
      - in: query
        name: order
        description: Show tender transactions ordered by processed_at in ascending or descending order.
        schema: {}
        required: false
      tags:
      - Tender
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_tender_transactions
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/tender_transactions.json:
    get:
      summary: Shopify Retrieves A List Of Tender Transactions
      description: https://shopify.dev/docs/admin-api/rest/reference/tendertransaction#index-unstable
      parameters:
      - in: query
        name: limit
        description: "The maximum number of results to retrieve.\n                  (default: 50, maximum: 250)"
        schema: {}
        required: false
      - in: query
        name: since_id
        description: Retrieve only transactions after the specified ID.
        schema: {}
        required: false
      - in: query
        name: processed_at_min
        description: Show tender transactions processed_at or after the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at_max
        description: Show tender transactions processed_at or before the specified date.
        schema: {}
        required: false
      - in: query
        name: processed_at
        description: Show tender transactions processed at the specified date.
        schema: {}
        required: false
      - in: query
        name: order
        description: Show tender transactions ordered by processed_at in ascending or descending order.
        schema: {}
        required: false
      tags:
      - Tender
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_tender_transactions
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
      description: Access token obtained via OAuth
