openapi: 3.2.0
info:
  title: Shopify Countries API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Countries
paths:
  /admin/api/2020-01/countries.json:
    get:
      summary: Shopify Retrieves A List Of Countries
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#index-2020-01
      parameters:
      - in: query
        name: since_id
        description: Restrict results to after the specified ID.
        schema: {}
        required: false
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Countries
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/countries.json:
    get:
      summary: Shopify Retrieves A List Of Countries
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#index-2020-04
      parameters:
      - in: query
        name: since_id
        description: Restrict results to after the specified ID.
        schema: {}
        required: false
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Countries
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/countries.json:
    get:
      summary: Shopify Retrieves A List Of Countries
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#index-2020-07
      parameters:
      - in: query
        name: since_id
        description: Restrict results to after the specified ID.
        schema: {}
        required: false
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Countries
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/countries.json:
    get:
      summary: Shopify Retrieves A List Of Countries
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#index-2020-10
      parameters:
      - in: query
        name: since_id
        description: Restrict results to after the specified ID.
        schema: {}
        required: false
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Countries
      responses:
        '200':
          description: ''
      operationId: get_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/countries.json:
    get:
      summary: Shopify Retrieves A List Of Countries
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#index-2021-01
      parameters:
      - in: query
        name: since_id
        description: Restrict results to after the specified ID.
        schema: {}
        required: false
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Countries
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/countries.json:
    get:
      summary: Shopify Retrieves A List Of Countries
      description: https://shopify.dev/docs/admin-api/rest/reference/store-properties/country#index-unstable
      parameters:
      - in: query
        name: since_id
        description: Restrict results to after the specified ID.
        schema: {}
        required: false
      - in: query
        name: fields
        description: Show only certain fields, specified by a comma-separated list of field names.
        schema: {}
        required: false
      tags:
      - Countries
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_countries
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
