openapi: 3.2.0
info:
  title: Shopify Belong API
  description: Explore Shopify's API reference and templating documentation. Shopify provides a range of software tools, app templates, example apps, and libraries to accelerate your development process. The Admin API lets you build apps and integrations that extend and enhance the Shopify admin.
  version: 2020-10
tags:
- name: Belong
paths:
  /admin/api/2020-01/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-01
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Belong
      responses:
        '200':
          description: ''
      operationId: deprecated_202001_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-04/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-04
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Belong
      responses:
        '200':
          description: ''
      operationId: deprecated_202004_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-07/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-07
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Belong
      responses:
        '200':
          description: ''
      operationId: deprecated_202007_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2020-10/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2020-10
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Belong
      responses:
        '200':
          description: ''
      operationId: get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/2021-01/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-2021-01
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Belong
      responses:
        '200':
          description: ''
      operationId: deprecated_202101_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
  /admin/api/unstable/metafields.json:
    get:
      summary: Shopify Retrieves A List Of Metafields That Belong To A Product Image Resource
      description: https://shopify.dev/docs/admin-api/rest/reference/metafield#index-unstable
      parameters:
      - in: query
        name: metafield[owner_id]
        schema:
          type: integer
        description: metafield[owner_id]
        required: false
      - in: query
        name: metafield[owner_resource]
        schema:
          type: string
        description: metafield[owner_resource]
        required: false
      tags:
      - Belong
      responses:
        '200':
          description: ''
      operationId: deprecated_unstable_get_metafields
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        ChooseTags: true
